
package com.smart.lisservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LisInfoService", targetNamespace = "http://impl.webservice.zcw.com/", wsdlLocation = "http://127.0.0.1:8080/lisservice/services/soap?wsdl")
public class LisInfoService_Service
    extends Service
{

    private final static URL LISINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISINFOSERVICE_EXCEPTION;
    private final static QName LISINFOSERVICE_QNAME = new QName("http://impl.webservice.zcw.com/", "LisInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/lisservice/services/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISINFOSERVICE_WSDL_LOCATION = url;
        LISINFOSERVICE_EXCEPTION = e;
    }

    public LisInfoService_Service() {
        super(__getWsdlLocation(), LISINFOSERVICE_QNAME);
    }

    public LisInfoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISINFOSERVICE_QNAME, features);
    }

    public LisInfoService_Service(URL wsdlLocation) {
        super(wsdlLocation, LISINFOSERVICE_QNAME);
    }

    public LisInfoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISINFOSERVICE_QNAME, features);
    }

    public LisInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LisInfoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LisInfoService
     */
    @WebEndpoint(name = "LisInfoServiceImplPort")
    public LisInfoService getLisInfoServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.zcw.com/", "LisInfoServiceImplPort"), LisInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LisInfoService
     */
    @WebEndpoint(name = "LisInfoServiceImplPort")
    public LisInfoService getLisInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.zcw.com/", "LisInfoServiceImplPort"), LisInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISINFOSERVICE_EXCEPTION!= null) {
            throw LISINFOSERVICE_EXCEPTION;
        }
        return LISINFOSERVICE_WSDL_LOCATION;
    }

}
